version: "3.7"
# The different services that make up our "network" of containers
services:
  neo:
    container_name: neo
    image: neo4j
    ports:
      - 7474:7474
      - 7687:7687
    # env_file:
    #   - backend/.env.neo4j
    volumes:
      - ./volumes/neo4j/db/data:/data
      - ./volumes/neo4j/db/conf:/conf
      - ./volumes/neo4j/db/logs:/logs
      - ./volumes/neo4j/db/plugins:/plugins

    environment:
      - NEO4J_AUTH=neo4j/alamakota

  keycloak:
    container_name: keycloak_service
    image: quay.io/keycloak/keycloak:21.1.1
    command: start-dev
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - DB_VENDOR=postgres
      - DB_ADDR=postgres
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_PASSWORD=password
    ports:
      - 8080:8080
    volumes:
      - ./volumes/keycloak_data:/opt/keycloak/data/
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=password
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data

volumes:
  neo4j_data:
  keycloak_data:
  postgres:
