version: "3.7"
# The different services that make up our "network" of containers
services:
  neo:
    container_name: neo
    image: neo4j
    ports:
      - 7474:7474
      - 7687:7687
    # env_file:
    #   - backend/.env.neo4j
    volumes:
      - ./volumes/neo4j/db/data:/data
      - ./volumes/neo4j/db/conf:/conf
      - ./volumes/neo4j/db/logs:/logs
      - ./volumes/neo4j/db/plugins:/plugins

    environment:
      # Raise memory limits
      - NEO4J_AUTH=neo4j/alamakota

  keycloak:
    container_name: keycloak_container
    image: quay.io/keycloak/keycloak:21.1.1
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - DB_VENDOR=POSTGRES
      - DB_ADDR=keycloak-db
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_PASSWORD=keycloak

    command:
      - start-dev

    depends_on:
      - keycloak-db

  keycloak-db:
    image: postgres:13
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak
    volumes:
      - ./volumes/postgresql_keycloack:/var/lib/postgresql/data

volumes:
  keycloak-db-data:
  neo4j_data:
